INSERT INTO Setting ([Name], [Value], LastEditedByUserId, UpdatedDate) VALUES
('ConcurrentEmailProcessCount', '1', 1, GETDATE()),
('EmailQueueSmtpFaultTolerance', '3', 1, GETDATE()),
('EnableEmailDomainChecking', 'True', 1, GETDATE()),
('InterestRate', '11.5', 1, GETDATE()),
('MaximumImagePayloadSizeMB', '10', 1, GETDATE()),
('MaximumImageSizeMB', '5', 1, GETDATE()),
('MinimumImageSizeB', '-128', 1, GETDATE()),
('NoReplyEmailEddress', 'KhumaloCraft noreply <no-reply@example.com>', 1, GETDATE()),
('Version', '1.0.0.0', 1, GETDATE()),
('PortalBaseUri', '', 1, GETDATE()),
('ImageServerBaseUri', 'https://kc-img-server.azurewebsites.net', 1, GETDATE()),
('ImageServerFallbackServer', 'https://kc-img-server-fallback.azurewebsites.net', 1, GETDATE()),
('BranchName', 'main', 1, GETDATE()),
('EnableTaskScheduler', 'True', 1, GETDATE()),
('SmtpServer', 'smtp.office365.com', 1, GETDATE()),
('SmtpLoginUsername', '', 1, GETDATE()),
('SmtpLoginPassword', '', 1, GETDATE()),
('VatRate', '0.15', 1, GETDATE()),
('AzureBlobStoragePrimary', '', 1, GETDATE()),
('RateLimitRequestsPerSecond', '30', 1, GETDATE()),
('DataProtectionKey', '', 1, GETDATE()),
('CookieProtectionKey', '', 1, GETDATE()),
('AzureAdCertThumbprint', '', 1, GETDATE()),
('AzureAdApplicationId', '', 1, GETDATE()),
('AzureAdDirectoryId', '', 1, GETDATE()),
('AzureKCResourceConnectionString', '', 1, GETDATE()),
('UseHostNameForCookies', 'True', 1, GETDATE());