INSERT INTO CraftworkCategory (Id, [Name], [Description])
VALUES	(1, 'Woodworking', 'Woodworking'),
		(2, 'Embroidery', 'Embroidery'),
		(3, 'Pottery', 'Pottery'),
		(4, 'Metalworking', 'Metalworking'),
		(5, 'Weaving', 'Weaving'),
		(6, 'Glassblowing', 'Glassblowing'),
		(7, 'TieDye', 'Tie Dye'),
		(8, 'Sculpture', 'Sculpture'),
		(9, 'Sewing', 'Sewing'),
		(10, 'Printmaking', 'Printmaking'),
		(11, 'Beadwork', 'Beadwork'),
		(12, 'RecycledCrafts', 'Recycled Crafts'),
		(13, 'Applique', 'Appliqué'),
		(14, 'Modelmaking', 'Modelmaking'),
		(15, 'Leatherworking', 'Leatherworking'),
		(16, 'Knitting', 'Knitting'),
		(17, 'TraditionalCrafts', 'Traditional Crafts'),
		(18, 'DigitalArt', 'Digital Art'),
		(19, 'MixedMedia', 'Mixed Media'),
		(20, 'Needlepoint', 'Needlepoint'),
		(21, 'StoneCarving', 'Stone Carving'),
		(22, 'PaperCrafts', 'Paper Crafts'),
		(23, 'Collage', 'Collage'),
		(24, 'Textiles', 'Textiles'),
		(25, 'Misc', 'Misc');